Ноздрова В. ИУ5-81Б

## Задание 1

In [ ]:
Variant<-15
set.seed(Variant)
k<-sample(c(4:9),1)
pp1<-runif(4)
pp2<-runif(3)
pp3<-runif(2)
p1<-pp1/sum(pp1)
p2<-c(c(0),pp2/sum(pp2))
p3<-c(c(0,0),pp3/sum(pp3))
p4<-c(0,0,0,1)
P<-data.frame()
P<-rbind(P,p1)
P<-rbind(P,p2)
P<-rbind(P,p3)
P<-rbind(P,p4)
rownames(P)<-c("p1","p2","p3","p4")
colnames(P)<-c("","","","")
View(P)
print(paste("k=",as.character(k)))

p1 0.08949103 0.4434355 0.2986517 0.1684218
p2 0.00000000 0.4804903 0.3961055 0.1234042
p3 0.00000000 0.0000000 0.4525245 0.5474755
p4 0.00000000 0.0000000 0.0000000 1.0000000

[1] "k= 8"

Граф состояний:


![Диаграмма без названия.drawio (13).png]()

В начальный момент времени ЭВМ находится в состоянии $S_1$. Тогда начальный вектор вероятностей $p(0) = \begin{pmatrix} 1&0&0&0 \end{pmatrix}$.

Таким образом,

$$
p(k) = p(0) \cdot
\begin{pmatrix}
p_{11} & p_{12} & p_{13} & p_{14} \\
0 & p_{22} & p_{23} & p_{24} \\
0 & 0 & p_{33} & p_{34}\\
0 & 0 & 0 & p_{44}
\end{pmatrix}^k =
\begin{pmatrix}
1&0&0&0
\end{pmatrix} \cdot
\begin{pmatrix} z_{11} & z_{12}  & z_{13}  & z_{14} \\
0 & z_{22} & z_{23} & z_{24} \\0 & 0 & z_{33} & z_{34}  \\
0 & 0 & 0 & z_{44}
\end{pmatrix} =
\begin{pmatrix}
z_{11} & z_{12} & z_{13} & z_{14}
\end{pmatrix} $$

где $z_{ij}$  - элементы $Z = P^k$.

Матрица $P$ верхнетреугольная, следовательно, $Z = P^k$ также верхнетреугольная.

Найдем диагональную матрицу $D$, $P = TDT^{-1}$:

$$ \begin{vmatrix}
p_{11}-\lambda & p_{12} & p_{13} & p_{14} \\
0 & p_{22}-\lambda & p_{23} & p_{24} \\
0 & 0 & p_{33}-\lambda & p_{34}\\
0 & 0 & 0 & p_{44}-\lambda
\end{vmatrix}
= (p_{11}-\lambda)(p_{22}-\lambda)(p_{33}-\lambda)(p_{44}-\lambda) = 0 $$

$\lambda_1 = p_{11}$:

$$\begin{pmatrix}
0 & p_{12} & p_{13} & p_{14} \\
0 & p_{22}-p_{11} & p_{23} & p_{24} \\
0 & 0 & p_{33}-p_{11} & p_{34}\\
0 & 0 & 0 & p_{44}-p_{11}
\end{pmatrix} ⋅
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4\end{pmatrix} =
\begin{pmatrix} 0\\0\\0\\0 \end{pmatrix}$$

$\begin{cases}
p_{12}x_2+p_{13}x_3+p_{14}x_4 = 0\\
(p_{22}-p{11})x_2+p_{23}x_3+p_{24}x_4 = 0\\
(p_{33}-p_{11})x_3 + p_{34}x_4 = 0\\
(p_{44}-p_{11})x_4 = 0
\end{cases}
⇔
\begin{cases}
x_1 = 1\\
x_2 = 0\\
x_3 = 0\\
x_4 = 0\\
\end{cases}
$

$\lambda_2 = p_{22}$:

$$\begin{pmatrix}
p_{11}-p_{22} & p_{12} & p_{13} & p_{14} \\
0 & 0 & p_{23} & p_{24} \\
0 & 0 & p_{33}-p_{22} & p_{34}\\
0 & 0 & 0 & p_{44}-p_{22}
\end{pmatrix} ⋅
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4\end{pmatrix} =
\begin{pmatrix} 0\\0\\0\\0 \end{pmatrix}$$

$\begin{cases}
(p_{11}-p_{22})x_1 + p_{12}x_2 + p_{13}x_3 + p_{14}x_4 = 0\\
p_{23}x_3 + p_{24}x_4=0\\
(p_{33}-p_{22})x_3 + p_{34}x_4 = 0\\
(p_{44}-p_{22})x_4 = 0 \\
\end{cases}
⇔
\begin{cases}
x_1 = \frac{p_{12}}{p_{22}-p_{11}}x_2 \\
x_2 = 1\\
x_3 = 0\\
x_4 = 0\\
\end{cases}
⇔
\begin{cases}
x_1 = \frac{p_{12}}{p_{22}-p_{11}} \\
x_2 = 1\\
x_3 = 0\\
x_4 = 0\\
\end{cases}
$

$\lambda_3 = p_{33}$:

$$\begin{pmatrix}
p_{11}-p_{33} & p_{12} & p_{13} & p_{14} \\
0 & p_{22}-p_{33} & p_{23} & p_{24} \\
0 & 0 & 0 & p_{34}\\
0 & 0 & 0 & p_{44}-p_{33}
\end{pmatrix} ⋅
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4\end{pmatrix} =
\begin{pmatrix} 0\\0\\0\\0 \end{pmatrix}$$

$\begin{cases}
(p_{11}-p_{33})x_1 + p_{12}x_2 + p_{13}x_3 + p_{14}x_4 = 0\\
(p_{22}-p_{33})x_2 + p_{23}x_3 + p_{24}x_4 = 0\\
p_{34}x_4 = 0\\
(p_{44}-p_{33})x_4 = 0 \\
\end{cases}
⇔
\begin{cases}
x_1 = \frac{p_{12}x_2 + p_{13}x_3}{p_{33}-p_{11}}\\
x_2 = \frac{p_{23}}{p_{33}-p_{22}}x_3\\
p_{34}x_4 = 0\\
(p_{44}-p_{33})x_4 = 0 \\
\end{cases}
⇔
\begin{cases}
x_1 = \frac{\frac{p_{12}p_{23}}{p_{33}-p_{22}}x_3 + p_{13}x_3}{p_{33}-p_{11}}\\
x_2 = \frac{p_{23}}{p_{33}-p_{22}}x_3\\
p_{34}x_4 = 0\\
(p_{44}-p_{33})x_4 = 0 \\
\end{cases}
⇔
\begin{cases}
x_1 = \frac{p_{12}p_{23}+p_{13}(p_{33}-p_{22})}{(p_{33}-p_{22})(p_{33}-p_{11})}\\
x_2 = \frac{p_{23}}{p_{33}-p_{22}}\\
x_3 = 1\\
x_4 = 0\\
\end{cases}
$

$\lambda_4 = p_{44}$:

$$\begin{pmatrix}
p_{11}-p_{44} & p_{12} & p_{13} & p_{14} \\
0 & p_{22}-p_{44} & p_{23} & p_{24} \\
0 & 0 & p_{33}-p_{44} & p_{34}\\
0 & 0 & 0 & 0\\
\end{pmatrix} ⋅
\begin{pmatrix} x_1 \\ x_2 \\ x_3 \\ x_4\end{pmatrix} =
\begin{pmatrix} 0\\0\\0\\0 \end{pmatrix}$$

$\begin{cases}
(p_{11}-p_{44})x_1 + p_{12}x_2 + p_{13}x_3 + p_{14}x_4 = 0\\
(p_{22}-p_{44})x_2 + p_{23}x_3 + p_{24}x_4 = 0\\
(p_{33}-p_{44})x_3 + p_{34}x_4 = 0\\
\end{cases}
⇔
\begin{cases}
x_1 = \frac{p_{12}x_2+p_{13}x_3+p_{14}x_4}{p_{44}-p_{11}}\\
x_2 = \frac{p_{23}x_3 + p_{24}x_4}{p_{44}-p_{22}}\\
x_3 = \frac{p_{34}}{p_{44}-p_{33}}x_4\\
\end{cases}
⇔$

$⇔
\begin{cases}
x_1 = \frac{p_{12}\frac{p_{23}p_{34}+p_{24}(p_{44}-p_{33})}{(p_{44}-p_{33})(p_{44}-p_{22})} + p_{13}\frac{p_{34}}{p_{44}-p_{33}} + p_{14}}{p_{44}-p_{11}}x_4\\
x_2 = \frac{p_{23}p_{34}+p_{24}(p_{44}-p_{33})}{(p_{44}-p_{33})(p_{44}-p_{22})}x_4\\
x_3 = \frac{p_{34}}{p_{44}-p_{33}}x_4\\
\end{cases}
⇔$

$⇔
\begin{cases}
x_1 = \frac{p_{12}p_{23}p_{34}+p_{12}p_{24}(p_{44}-p_{33})+p_{13}p_{34}(p_{44}-p_{22})+p_{14}(p_{44}-p_{33})(p_{44}-p_{22})}{(p_{44}-p_{11})(p_{44}-p_{33})(p_{44}-p_{22})}\\
x_2 = \frac{p_{23}p_{34}+p_{24}(p_{44}-p_{33})}{(p_{44}-p_{33})(p_{44}-p_{22})}\\
x_3 = \frac{p_{34}}{p_{44}-p_{33}}\\
x_4 = 1\\
\end{cases}
$

Таким образом, искомая диагональная матрица $D$:

$$D =
\begin{pmatrix}
\lambda_1 & 0 & 0 & 0\\
0 & \lambda_2 & 0 & 0\\
0 & 0 & \lambda_3 & 0\\
0 & 0 & 0 & \lambda_4\\
\end{pmatrix} =
\begin{pmatrix}
p_{11} & 0 & 0 & 0\\
0 & p_{22} & 0 & 0\\
0 & 0 & p_{33} & 0\\
0 & 0 & 0 & p_{44}\\
\end{pmatrix}$$

Матрица перехода к базису собственных векторов $T$:

$$T=
\begin{pmatrix}
1 & \frac{p_{12}}{p_{22}-p_{11}} &
\frac{p_{12}p_{23}+p_{13}(p_{33}-p_{22})}{(p_{33}-p_{22})(p_{33}-p_{11})} &
\frac{p_{12}p_{23}p_{34}+p_{12}p_{24}(p_{44}-p_{33})+p_{13}p_{34}(p_{44}-p_{22})+p_{14}(p_{44}-p_{33})(p_{44}-p_{22})}
{(p_{44}-p_{11})(p_{44}-p_{33})(p_{44}-p_{22})} \\
0 & 1 & \frac{p_{23}}{p_{33}-p_{22}} &
\frac{p_{23}p_{34}+p_{24}(p_{44}-p_{33})}{(p_{44}-p_{33})(p_{44}-p_{22})}\\
0 & 0 & 1 & \frac{p_{34}}{p_{44}-p_{33}} \\
0 & 0 & 0 & 1\\
\end{pmatrix}$$

Матрица $T^{-1}$:

[ Wolfram](https://www.wolframalpha.com/input?i2d=true&i=Power%5B%7B%7B1%2CDivide%5Bp_12%2Cp_22-p_11%5D%2CDivide%5Bp_12*p_23%2Bp_13%5C%2840%29p_33-p_22%5C%2841%29%2C%5C%2840%29p_33-p_22%5C%2841%29%5C%2840%29p_33-p_11%5C%2841%29%5D%2CDivide%5Bp_12*p_23*p_34%2Bp_12*p_24%5C%2840%29p_44-p_33%5C%2841%29%2Bp_13*p_34%5C%2840%29p_44-p_22%5C%2841%29%2Bp_14%5C%2840%29p_44-p_33%5C%2841%29%5C%2840%29p_44-p_22%5C%2841%29%2C%5C%2840%29p_44-p_11%5C%2841%29%5C%2840%29p_44-p_33%5C%2841%29%5C%2840%29p_44-p_22%5C%2841%29%5D%7D%2C%7B0%2C1%2CDivide%5Bp_23%2Cp_33-p_22%5D%2CDivide%5Bp_23*p_34%2Bp_24%5C%2840%29p_44-p_33%5C%2841%29%2C%5C%2840%29p_44-p_33%5C%2841%29%5C%2840%29p_44-p_22%5C%2841%29%5D%7D%2C%7B0%2C0%2C1%2CDivide%5Bp_34%2Cp_44-p_33%5D%7D%2C%7B0%2C0%2C0%2C1%7D%7D%2C-1%5D)

$$
T^{-1} =
\begin{pmatrix}
1 & \frac{p_{12}}{p_{11}-p_{22}} &
\frac{p_{11}p_{13}-p_{22}p_{13}+p_{12}p_{23}}{(p_{11}-p_{22})(p_{11}-p_{33})}
&
\frac{p_{14}p_{11}^2 + p_{11}p_{12}p_{24} - p_{11}p_{14}p_{22}-p_{11}p_{14}p_{33}+p_{11}p_{13}p_{34}+p_{14}p_{22}p_{33}-p_{12}p_{24}p_{33}-p_{13}p_{22}p_{34}+p_{12}p_{23}p_{34}}{(p_{11}-p_{22})(p_{11}-p_{33})(p_{11}-p_{44}} \\
0 & 1 & \frac{p_{23}}{p_{22}-p_{33}} &
\frac{p_{22}p_{24}-p_{33}p_{24}+p_{23}p_{34}}{(p_{22}-p_{33})(p_{22}-p_{44})} \\
0 & 0 & 1 & \frac{p_{34}}{p_{33}-p_{44}}\\
0 & 0 & 0 & 1 \\
\end{pmatrix}$$

$P^k = Z = TD^kT^{-1}$

$Z = \begin{pmatrix}
1 & \frac{p_{12}}{p_{22}-p_{11}} &
\frac{p_{12}p_{23}+p_{13}(p_{33}-p_{22})}{(p_{33}-p_{22})(p_{33}-p_{11})} &
\frac{p_{12}p_{23}p_{34}+p_{12}p_{24}(p_{44}-p_{33})+p_{13}p_{34}(p_{44}-p_{22})+p_{14}(p_{44}-p_{33})(p_{44}-p_{22})}
{(p_{44}-p_{11})(p_{44}-p_{33})(p_{44}-p_{22})} \\
0 & 1 & \frac{p_{23}}{p_{33}-p_{22}} &
\frac{p_{23}p_{34}+p_{24}(p_{44}-p_{33})}{(p_{44}-p_{33})(p_{44}-p_{22})}\\
0 & 0 & 1 & \frac{p_{34}}{p_{44}-p_{33}} \\
0 & 0 & 0 & 1\\
\end{pmatrix}
\begin{pmatrix}
p_{11}^k & 0 & 0 & 0\\
0 & p_{22}^k & 0 & 0\\
0 & 0 & p_{33}^k & 0\\
0 & 0 & 0 & p_{44}^k\\
\end{pmatrix} ⋅ T^{-1} =
$

$=
\begin{pmatrix}
p_{11}^k & p_{22}^k \frac{p_{12}}{p_{22}-p_{11}} &
p_{33}^k \frac{p_{12}p_{23}+p_{13}(p_{33}-p_{22})}{(p_{33}-p_{22})(p_{33}-p_{11})} &
p_{44}^k \frac{p_{12}p_{23}p_{34}+p_{12}p_{24}(p_{44}-p_{33})+p_{13}p_{34}(p_{44}-p_{22})+p_{14}(p_{44}-p_{33})(p_{44}-p_{22})}
{(p_{44}-p_{11})(p_{44}-p_{33})(p_{44}-p_{22})} \\
0 & p_{22}^k & p_{33}^k\frac{p_{23}}{p_{33}-p_{22}} &  p_{44}^k \frac{p_{23}p_{34}+p_{24}(p_{44}-p_{33})}{(p_{44}-p_{33})(p_{44}-p_{22})} \\
0 & 0 & p_{33}^k & p_{44}^k \frac{p_{34}}{p_{44}-p_{33}} \\
0 & 0 & 0 & p_{44}^k \\
\end{pmatrix} ⋅ T^{-1}
$

$$p(k) = p(0) ⋅ P^k = p(0) ⋅ Z = \begin{pmatrix} 1 & 0 & 0 & 0 \end{pmatrix} ⋅ Z = \begin{pmatrix} z_{11} & z_{12} & z_{13} & z_{14} \end{pmatrix}$$

$z_{11} = p_{11}^k$

$z_{12} =p_{11}^k\frac{p_{12}}{p_{11}-p_{22}} + p_{22}^k \frac{p_{12}}{p_{22}-p_{11}} = p_{12}\frac{p_{11}^k-p_{22}^k}{p_{11}-p_{22}} $

$z_{13} = p_{11}^k \frac{p_{11}p_{13}-p_{22}p_{13}+p_{12}p_{23}}{(p_{11}-p_{22})(p_{11}-p_{33})} + p_{22}^k \frac{p_{12}}{p_{22}-p_{11}} \cdot \frac{p_{23}}{p_{22}-p_{33}} + p_{33}^k \frac{p_{12}p_{23}+p_{13}(p_{33}-p_{22})}{(p_{33}-p_{22})(p_{33}-p_{11})}
$

$ z_{14} = p_{11}^k \frac{p_{14}p_{11}^2 + p_{11}p_{12}p_{24} - p_{11}p_{14}p_{22}-p_{11}p_{14}p_{33}+p_{11}p_{13}p_{34}+p_{14}p_{22}p_{33}-p_{12}p_{24}p_{33}-p_{13}p_{22}p_{34}+p_{12}p_{23}p_{34}}{(p_{11}-p_{22})(p_{11}-p_{33})(p_{11}-p_{44}} + p_{22}^k \frac{p_{12}}{p_{22}-p_{11}} \cdot \frac{p_{22}p_{24}-p_{33}p_{24}+p_{23}p_{34}}{(p_{22}-p_{33})(p_{22}-p_{44})} + $
$ + p_{33}^k \frac{p_{12}p_{23} + p_{13}(p_{33}-p_{22})}{(p_{33}-p_{22})(p_{33}-p_{11})} \cdot  \frac{p_{34}}{p_{33}-p_{44}} + p_{44}^k \frac{p_{12}p_{23}p_{34}+p_{12}p_{24}(p_{44}-p_{33})+p_{13}p_{34}(p_{44}-p_{22})+p_{14}(p_{44}-p_{33})(p_{44}-p_{22})}
{(p_{44}-p_{11})(p_{44}-p_{33})(p_{44}-p_{22})}
$

In [ ]:
pm <- data.matrix(P)

In [ ]:
p0 <- c(1,0,0,0)

In [ ]:
print(p0)
print(pm)

[1] 1 0 0 0

p1 0.08949103 0.4434355 0.2986517 0.1684218
p2 0.00000000 0.4804903 0.3961055 0.1234042
p3 0.00000000 0.0000000 0.4525245 0.5474755
p4 0.00000000 0.0000000 0.0000000 1.0000000

In [ ]:
t12 <- pm[1,2]/(pm[1,1]-pm[2,2])
t13 <- (pm[1,1]*pm[1,3]-pm[2,2]*pm[1,3]+pm[1,2]*pm[2,3])/((pm[1,1]-pm[2,2])*(pm[1,1]-pm[3,3]))
t14 <- (pm[1,4]*pm[1,1]^2+pm[1,1]*pm[1,2]*pm[2,4] - pm[1,1]*pm[1,4]*pm[2,2]-pm[1,1]*pm[1,4]*pm[3,3]+pm[1,1]*pm[1,3]*pm[3,4]+pm[1,4]*pm[2,2]*pm[3,3]-pm[1,2]*pm[2,4]*pm[3,3]-pm[1,3]*pm[2,2]*pm[3,4]+pm[1,2]*pm[2,3]*pm[3,4])/((pm[1,1]-pm[2,2])*(pm[1,1]-pm[3,3])*(pm[1,1]-pm[4,4]))
t23 <- pm[2,3]/(pm[2,2]-pm[3,3])
t24 <- (pm[2,2]*pm[2,4]-pm[3,3]*pm[2,4]+pm[2,3]*pm[3,4])/((pm[2,2]-pm[3,3])*(pm[2,2]-pm[4,4]))
t34 <- pm[3,4]/(pm[3,3]-pm[4,4])
td12 <- -t12
td13 <- (pm[1,2]*pm[2,3]+pm[1,3]*(pm[3,3]-pm[2,2])) / ((pm[3,3]-pm[2,2])*(pm[3,3]-pm[1,1]))
td14 <- (pm[1,2]*pm[2,3]*pm[3,4] + pm[1,2]*pm[2,4]*(pm[4,4]-pm[3,3])+pm[1,3]*pm[3,4]*(pm[4,4]-pm[2,2])+pm[1,4]*(pm[4,4]-pm[3,3])*(pm[4,4]-pm[2,2]))/((pm[4,4]-pm[1,1])*(pm[4,4]-pm[3,3])*(pm[4,4]-pm[2,2]))

z11 <- function(r) {return(pm[1,1]^r)}

z12 <- function(r) {return(pm[1,1]^r * t12 + pm[2,2]^r * td12)}

z13 <- function(r) {return(pm[1,1]^r * t13 + pm[2,2]^r * td12 * t23 + pm[3,3]^r * td13)}

z14 <- function(r) {return(pm[1,1]^r * t14 + pm[2,2]^r * td12 * t24 + pm[3,3]^r * td13 * t34 + pm[4,4]^r * td14)}

In [ ]:
install.packages("matrixcalc")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
library(matrixcalc)

In [ ]:
model <- function(steps) {
N <- 1000000
ps<-rep(c(0), times=4)
for (i in 1:N)
{
  s <- 1
  for (j in 1:steps)
  {
    s <-sample(c(1:4),size=1, prob=pm[s,])
  }
  ps[s]<-ps[s]+1
}
return(ps/N)
}

Вероятности состояний ЭВМ после $k-2$ осмотров:

In [ ]:
#теоретически
z11(k-2); z12(k-2); z13(k-2); z14(k-2)

[1] 5.136617e-07

[1] 0.01395546

[1] 0.05617069

[1] 0.9298733

In [ ]:
#численно
p0 %*% matrix.power(pm,k-2)

[1,] 5.136617e-07 0.01395546 0.05617069 0.9298733

In [ ]:
#экспериментально
model(k-2)

[1] 0.000001 0.014081 0.055907 0.930011

Вероятности состояний ЭВМ после $k-1$ осмотров:

In [ ]:
#теоретически
z11(k-1); z12(k-1); z13(k-1); z14(k-1)

[1] 4.596812e-08

[1] 0.006705693

[1] 0.0309466

[1] 0.9623477

In [ ]:
#численно
p0 %*% matrix.power(pm,k-1)

[1,] 4.596812e-08 0.006705693 0.0309466 0.9623477

In [ ]:
#экспериментально
model(k-1)

[1] 0.000000 0.006844 0.031066 0.962090

Вероятности состояний ЭВМ после $k$ осмотров:

In [ ]:
#теоретически
z11(k); z12(k); z13(k); z14(k)

[1] 4.113734e-09

[1] 0.003222041

[1] 0.01666027

[1] 0.9801177

In [ ]:
#численно
p0 %*% matrix.power(pm,k)

[1,] 4.113734e-09 0.003222041 0.01666027 0.9801177

In [ ]:
#экспериментально
model(k)

[1] 0.000000 0.003274 0.016725 0.980001

# Задание 2

In [ ]:
Variant<-15
set.seed(Variant)
k<-sample(c(10:25),1)
t1<-sample(c(14:20),1)
t2<-sample(c(2:5),1)
View(data.frame(k,t1,t2))

  k  t1 t2
1 14 20 3

In [ ]:
#подстройка параметра t1 таким образом, чтобы lambda < mu
t1 <- 56

Интенсивность потока подготовки программ $\lambda = \frac{k}{t_1}$, интенсивность потока выполнения программ $\mu = \frac{1}{t_2}$

$\rho = \frac{\lambda}{\mu}$

In [ ]:
l <- k/t1
m <- 1/t2
rho <- l/m
rho

[1] 0.75

Найдем вероятность того, что программа не будет выполнена сразу же, то есть в системе больше одной программы:

 $$P_0 = 1 - \rho $$

 $$P_1 = \rho \cdot (1 - \rho)$$

 $$P_{k>1} = 1 - P_0 - P_1 = 1 - (1 - \rho + \rho(1 - \rho)) = 1 - (1 - \rho^2) = \rho^2$$

In [ ]:
rho^2

[1] 0.5625

Найдем среднее время до получения пользователем результатов реализации, то есть среднее время программы в системе:

$$ T_{сист} = \frac{1}{\mu(1-\rho)} $$

In [ ]:
T_sist

[1] 12

Найдем среднее количество программ, ожидающих выполнения на сервере, то есть среднюю длину очереди:

$$ L_{оч} = \frac{\rho^2}{(1-\rho)} $$

In [ ]:
L <- rho^2/(1-rho); L

[1] 2.25

Проведем моделирование системы, и убедимся, что экспериментальные данные совпадают с теоретическими расчетами:

In [ ]:
#install.packages("simmer")
library(simmer)

In [ ]:
#моделирование
SIM_TIME = 1000000

program <- trajectory("program's path") %>%
   set_global('count', 1, mod='+') %>%
   branch(function() ifelse(get_queue_count(firm, "server") > 0, 1, 0),
          continue = TRUE,
          trajectory() %>%
          set_global('nonzero',1, mod='+')
   ) %>%
   seize("server") %>%
   timeout(function() rexp(1, 1/t2)) %>%
   release("server")

distr <- function() rexp(1, 1/t1)
firm <- simmer("firm") %>%
   add_global("count",0) %>%
   add_global("nonzero",0) %>%
   add_resource("server", mon=TRUE) %>%
   add_generator(paste0("Programmer№", c(1:k)," "), program, from(distr, distr), mon=2)

firm %>% run(until = SIM_TIME)

simmer environment: firm | now: 1e+06 | next: 1000002.33526292
{ Monitor: in memory }
{ Resource: server | monitored: TRUE | server status: 1(1) | queue status: 10(Inf) }
{ Source: Programmer№1  | monitored: 2 | n_generated: 17851 }
{ Source: Programmer№2  | monitored: 2 | n_generated: 17703 }
{ Source: Programmer№3  | monitored: 2 | n_generated: 17713 }
{ Source: Programmer№4  | monitored: 2 | n_generated: 17948 }
{ Source: Programmer№5  | monitored: 2 | n_generated: 17803 }
{ Source: Programmer№6  | monitored: 2 | n_generated: 18052 }
{ Source: Programmer№7  | monitored: 2 | n_generated: 17902 }
{ Source: Programmer№8  | monitored: 2 | n_generated: 17897 }
{ Source: Programmer№9  | monitored: 2 | n_generated: 17821 }
{ Source: Programmer№10  | monitored: 2 | n_generated: 17787 }
{ Source: Programmer№11  | monitored: 2 | n_generated: 17980 }
{ Source: Programmer№12  | monitored: 2 | n_generated: 17804 }
{ Source: Programmer№13  | monitored: 2 | n_generated: 17709 }
{ Source: Programmer№14  | monitored: 2 | n_generated: 17816 }
{ Global: count | schedule: FALSE | initial value: 0 }
{ Global: nonzero | schedule: FALSE | initial value: 0 }

In [ ]:
prog_stats <- get_mon_arrivals(firm)
prog_stats <- transform(prog_stats, waiting_time = end_time - start_time)
cat(paste("T_сист:", mean(prog_stats$waiting_time), '\n'))

server_stats <- get_mon_resources(firm)
cat(paste("L_оч:", mean(server_stats$queue), '\n'))

cat(paste("P_k>1:", get_global(firm, "nonzero")/get_global(firm, "count")))

T_сист: 12.073067655764
L_оч: 2.63885268841098
P_k>1: 0.563229665454895

# Задание 3

In [ ]:
Variant<-15
set.seed(Variant)
pp<-runif(3)
p1<-pp[1]/sum(pp)
p2<-pp[2]/sum(pp)
p3<-pp[3]/sum(pp)
k<-sample(c(4:8),1)
m<-sample(c(1:k),1)
View(data.frame(p1,p2,p3,k,m))

  p1        p2        p3        k m
1 0.3414087 0.1105932 0.5479982 5 1

Последовательность положений точки можно рассматривать как неоднородную цепь Маркова. Переходные вероятности $P_{i,i}=p_1, P_{i,i+1}=p_2, P_{i,i-1}=p_3$, остальные равны нулю. Искомая вероятность $P(k) = x_{-m}(k)+x_{-m+1}(k)+...+x_{-1}(k)+x_0(k)+x_1(k)+...+x_{m-1}(k)+x_m(k)$, где $x_i(k)$ - вероятность нахождения точки в координате $i$ на $k$-м шаге.

$x_i(k) = x_{i-1}(k-1)p_2+x_i(k-1)p_1+x_{i+1}(k-1)p_3$

Начальное положение точки $x_0(0) = 1$

На первом шаге $x_{-1}(1)=p_3, x_{0}(1)=p_1, x_1(1)=p_2$

In [ ]:
#вероятности нахождения точки на первом шаге
ax <- function(j)
{
  if (j==-1) return(p3)
  else if (j==0) return(p1)
  else if (j==1) return (p2)
  else return(0)
}

#рекурсивное вычисление вероятностей нахождения точки в i-той координате на t-м шаге
rec <- function(i, t) {
  if (t==1)
    res <- ax(i-1)*p2+ax(i)*p1+ax(i+1)*p3
  else
    res <- rec(i-1,t-1)*p2+rec(i,t-1)*p1+rec(i+1,t-1)*p3
  return(res)
}

In [ ]:
crd <- c((-1*m):m)
ans <- 0
for (y in (-1*m):m)
{
  ans <- ans + rec(y, k-1)
}
ans

[1] 0.2989916

Смоделируем систему и сравним полученный ответ с теоретическим:

In [ ]:
N <- 500000
count <- 0

for (i in 1:N)
  {
    x <- 0
    for (i in 1:k)
    {
      dx <- sample(c(-1:1), 1, prob=c(p3,p1,p2))
      x <- x + dx
    }
    if ((x>=-1*m) && (x<= m))
      count <- count+1
  }
count/N;

[1] 0.298918